#!/usr/bin/env bash

highlight() {
	set +x

	local IFS
	local set_bold
	local reset

	set_bold="$(tput setaf 3)$(tput bold)"
	reset="$(tput sgr0)"

	set -- "${1:-/dev/stdin}" "${@:2}"

	for f in "$@"; do
		while read -r line; do
			printf "%s%s%s\n" "$set_bold" "$line" "$reset"
		done < "$f"
	done
}
